name: roadsafe_alerts
description: RoadSafe Alerts — privacy-respecting road-safety alerts (read-only Firestore)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'   # <-- compatible Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # MAP & LOCATION
  flutter_map: 7.0.2
  latlong2: 0.9.1
  geolocator: 12.0.0
  permission_handler: 11.3.0

  # FIREBASE (lecture seule + notif topic optionnel)
  firebase_core: 2.24.2
  cloud_firestore: 4.13.6
  firebase_messaging: 14.7.10

  # NOTIFICATIONS LOCALES
  flutter_local_notifications: 17.2.2

  # STOCKAGE LOCAL & OUTILS
  shared_preferences: 2.2.2
  flutter_dotenv: 5.1.0
  timeago: 3.7.1

  # (Optionnel) Icônes iOS
  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true

  # Génération i18n (utilisera l10n/*.arb)
  generate: true

  assets:
    - assets/images/roadsafe_logo.png
